#!/usr/bin/env python3
"""Render the registers and the pins of the repository as LaTeX chapters of the blueprint.

    python3 blueprint/scripts/render_registers.py            # (re)write blueprint/src/generated/
    python3 blueprint/scripts/render_registers.py --check    # exit 1 if a generated file is stale

Inputs (paths relative to the repository root) and outputs (under blueprint/src/generated/):

    doc/SHIPPING-CHANGES.md                  -> shipping-changes.tex
    doc/DIVERGENCES.md                       -> divergences.tex
    lean-toolchain, lake-manifest.json       -> pins.tex

The Markdown of a register is converted as it is, block by block: headings, paragraphs, bullet and
numbered lists (nested by indentation), indented code blocks, inline code, bold and links. A
construct outside this subset (a table, a fenced code block, an HTML tag, an unbalanced `**`, a
character without a LaTeX rendering) stops the script with an error that names the line, so that a
register is never rendered partially. Two rules are specific to the registers:

  * the `#` title of a register is replaced by the chapter title;
  * in doc/DIVERGENCES.md, the entries are the `###` sections under `## Entries`; the prose under
    `## Entries` before the first entry is rendered as it is, followed by a table of the entries.
    An `## Entries` section with neither prose nor entries is rendered as "The register has no
    entries."

Inline code that cites the Lean sources becomes a citation that the web version links (README,
"Links to the Lean sources"; macros/common.tex), outside headings: a declaration by its full name
(`EraseProof.<name>`, `Lean4Lean.<name>`, `Erasure.<name>`, the forms the registers use) that has a
row in generated/lean-locations.tsv (audit.py --update locates every such name of the registers
that is a declaration: decl_candidates) becomes \\leandecl; a .lean file by its path from the root of a repository (this repository, where the file
exists; lean4lean, batteries and Lean by the first component of the path, scripts/leanlinks.py),
with lines or not, \\leanfile or \\leanloc; `:<lines>` after such a file, in the same paragraph,
\\leanlinesof. Any other code stays \\texttt. The audit checks every citation.

The blueprint build (blueprint/build.sh) runs this script first; the audit runs it with --check.
"""
import collections, json, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import leanlinks  # noqa: E402

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(REPO, 'blueprint', 'src', 'generated')
HEADER = '%% Generated by blueprint/scripts/render_registers.py from {src}. Do not edit.\n'


class RenderError(Exception):
    pass


# Characters outside ASCII and their LaTeX renderings (valid in text and inside \texttt).
UNICODE = {
    '\u25a1': r'\ensuremath{\Box}',            # box
    '\u2026': r'\ldots{}',                    # ellipsis
    '\u03bb': r'\ensuremath{\lambda}',
    '\u03b7': r'\ensuremath{\eta}',
    '\u03b1': r'\ensuremath{\alpha}',
    '\u03b2': r'\ensuremath{\beta}',
    '\u03b9': r'\ensuremath{\iota}',
    '\u03b4': r'\ensuremath{\delta}',
    '\u03b6': r'\ensuremath{\zeta}',
    '\u03c1': r'\ensuremath{\rho}',
    '\u03a0': r'\ensuremath{\Pi}',
    '\u0393': r'\ensuremath{\Gamma}',
    '\u03a3': r'\ensuremath{\Sigma}',
    '\u2192': r'\ensuremath{\to}',
    '\U0001d4d4': r'\ensuremath{\mathcal{E}}',   # Letouzey's extraction function
    '\u2190': r'\ensuremath{\leftarrow}',
    '\u21a6': r'\ensuremath{\mapsto}',
    '\u21d2': r'\ensuremath{\Rightarrow}',
    '\u00d7': r'\ensuremath{\times}',
    '\u27e8': r'\ensuremath{\langle}',
    '\u27e9': r'\ensuremath{\rangle}',
    '\u2200': r'\ensuremath{\forall}',
    '\u2203': r'\ensuremath{\exists}',
    '\u2264': r'\ensuremath{\le}',
    '\u2265': r'\ensuremath{\ge}',
    '\u2260': r'\ensuremath{\ne}',
    '\u2261': r'\ensuremath{\equiv}',
    '\u2248': r'\ensuremath{\approx}',
    '\u2225': r'\ensuremath{\parallel}',     # squash brackets
    '\u2208': r'\ensuremath{\in}',
    '\u2227': r'\ensuremath{\wedge}',
    '\u2228': r'\ensuremath{\vee}',
    '\u00ac': r'\ensuremath{\neg}',
    '\u22a2': r'\ensuremath{\vdash}',
    '\u25b8': r'\ensuremath{\blacktriangleright}',
    '\u25c0': r'\ensuremath{\blacktriangleleft}',   # Letouzey's invariant
    '\u00b7': r'\ensuremath{\cdot}',
    '\u2081': r'\ensuremath{_1}',
    '\u2082': r'\ensuremath{_2}',
    '\u2099': r'\ensuremath{_n}',
    '\u207b': r'\ensuremath{^{-}}',          # CIC with superscript minus
    '\u00a7': r'\S{}',
    '\u00ab': r'\ensuremath{\langle\!\langle}',   # Lean name quotes
    '\u00bb': r'\ensuremath{\rangle\!\rangle}',
    '\u2013': '--',
    '\u2014': '---',
    '\u2018': '`', '\u2019': "'", '\u201c': '``', '\u201d': "''",
    '\u00e9': r"\'e", '\u00e8': r'\`e', '\u00ef': r'\"i', '\u00f6': r'\"o', '\u00fc': r'\"u',
    '\u00a0': '~',
}
SPECIAL = {'\\': r'\textbackslash{}', '{': r'\{', '}': r'\}', '$': r'\$', '&': r'\&', '#': r'\#',
           '%': r'\%', '_': r'\_', '~': r'\textasciitilde{}', '^': r'\textasciicircum{}'}


def esc(text, where, code=False):
    out = []
    for i, ch in enumerate(text):
        if ch in SPECIAL:
            out.append(SPECIAL[ch])
            if code and ch == '_':
                out.append(r'\allowbreak{}')
        elif ord(ch) > 127:
            if ch not in UNICODE:
                raise RenderError(f'{where}: no LaTeX rendering for {ch!r} (U+{ord(ch):04X}); '
                                  'add it to UNICODE in render_registers.py')
            out.append(UNICODE[ch])
        elif code and ch == '-' and i + 1 < len(text) and text[i + 1] == '-':
            out.append('-{}')
        elif code and ch in '<>|"':
            out.append({'<': r'\textless{}', '>': r'\textgreater{}', '|': r'\textbar{}',
                        '"': r'\textquotedbl{}'}[ch])
        else:
            out.append(ch)
            if code and ch == '/' and i + 1 < len(text):
                out.append(r'\allowbreak{}')
    return ''.join(out)


TABLE_ROWS = 30


def table(spec, header, rows):
    """A booktabs table, split into tables of at most TABLE_ROWS rows (plasTeX cannot render
    longtable, and a tabular does not break across pages)."""
    out = []
    for k in range(0, len(rows), TABLE_ROWS):
        out.append(f'\\begin{{tabular}}{{{spec}}}\n\\toprule\n{header} \\\\\n\\midrule\n'
                   + '\n'.join(rows[k:k + TABLE_ROWS]) + '\n\\bottomrule\n\\end{tabular}\n\n')
    return ''.join(out)


def plain(text):
    """ASCII text for a PDF bookmark: inline markup and non-ASCII characters dropped."""
    text = text.replace('`', '').replace('**', '')
    return esc(''.join(ch if ord(ch) < 128 else ' ' for ch in text), 'bookmark')


# Citations of the Lean sources in inline code (module docstring).
DECL_CITE = re.compile(r"(?:EraseProof|Lean4Lean|Erasure)(?:\.[A-Za-z0-9_'?!\u2080-\u2083\u03c3\u03b1]+)+")
FILE_CITE = re.compile(r'(?P<path>[A-Za-z0-9_./-]+\.[A-Za-z]+)(?::(?P<lines>[0-9][0-9,:-]*))?')
MORE_LINES = re.compile(r':(?P<lines>' + leanlinks.LINES.pattern + ')')


def decl_candidates():
    """The inline code of the registers that may cite a declaration by its full name."""
    out = set()
    for src in ('doc/SHIPPING-CHANGES.md', 'doc/DIVERGENCES.md'):
        for c in re.findall(r'`([^`]*)`', '\n'.join(read(src))):
            if DECL_CITE.fullmatch(c) and not c.endswith('.lean'):
                out.add(c)
    return out


LOCATED = {}


def located(name):
    """Whether a name has a row in generated/lean-locations.tsv."""
    if 'names' not in LOCATED:
        LOCATED['names'] = set(leanlinks.read_locations())
    return name in LOCATED['names']


def lean_file(path):
    """Whether a path cites a Lean file that the web version links: a .lean file of a package or
    of Lean (by its first component), or of this repository where it exists."""
    return (path.endswith('.lean') and not path.startswith(('/', '.'))
            and (leanlinks.repo_of_path(path) != leanlinks.SELF or os.path.isfile(os.path.join(REPO, path))))


def code(c, where, state):
    """Inline code c: a citation of the Lean sources (module docstring) when state is a dict
    (it remembers the file cited last in the paragraph), else \\texttt."""
    if state is not None:
        if DECL_CITE.fullmatch(c) and not c.endswith('.lean') and located(c):
            return r'\leandecl{' + c + '}'
        m = FILE_CITE.fullmatch(c)
        if m:
            path, lines = m.group('path'), m.group('lines')
            state['file'] = path if lean_file(path) else None
            if state['file'] and lines is None:
                return r'\leanfile{' + esc(path, where, code=True) + '}'
            if state['file'] and leanlinks.LINES.fullmatch(lines):
                return r'\leanloc{' + esc(path, where, code=True) + '}{' + lines + '}'
            state['file'] = None
        m = MORE_LINES.fullmatch(c)
        if m and state.get('file'):
            return r'\leanlinesof{' + esc(state['file'], where, code=True) + '}{' + m.group('lines') + '}'
    return r'\texttt{' + esc(c, where, code=True) + '}'


def inline(text, where, cite=True):
    """Inline Markdown: `code`, **bold**, [text](url); inline code that cites the Lean sources
    becomes a citation when cite (not in headings and titles, whose links would nest)."""
    if '<' in re.sub(r'`[^`]*`', '', text) and re.search(r'<[A-Za-z/][^>]*>', re.sub(r'`[^`]*`', '', text)):
        raise RenderError(f'{where}: HTML tag in {text[:60]!r}')
    parts = re.split(r'(`[^`]*`)', text)
    if any(p.count('`') % 2 for p in parts if not (p.startswith('`') and p.endswith('`') and len(p) > 1)):
        raise RenderError(f'{where}: unbalanced backtick in {text[:60]!r}')
    out, bold, state = [], False, ({} if cite else None)
    for p in parts:
        if len(p) > 1 and p.startswith('`') and p.endswith('`'):
            out.append(code(p[1:-1], where, state))
            continue
        pos = 0
        for m in re.finditer(r'\*\*|\[([^\]]*)\]\(([^)\s]*)\)', p):
            out.append(esc(p[pos:m.start()], where))
            if m.group(0) == '**':
                out.append('}' if bold else r'\textbf{')
                bold = not bold
            else:
                out.append(r'\href{' + m.group(2).replace('%', r'\%').replace('#', r'\#') + '}{'
                           + esc(m.group(1), where) + '}')
            pos = m.end()
        out.append(esc(p[pos:], where))
    if bold:
        raise RenderError(f'{where}: unbalanced ** in {text[:60]!r}')
    return ''.join(out)


LIST_RE = re.compile(r'^( *)([-*+]|\d+\.) +(.*)$')


def blocks(lines, src, first_line):
    """Parse Markdown lines into a list of blocks:
    ('h', level, text, lineno), ('p', text, lineno), ('code', [lines], lineno),
    ('list', ordered, items) with items = [[block, ...], ...]."""
    out, stack, i, prev_blank = [], [], 0, True
    # stack entries: dict(marker=indent, content=indent, ordered=bool, items=[[...]])

    def close_all():
        stack.clear()

    while i < len(lines):
        raw = lines[i].rstrip('\n')
        where = f'{src}:{first_line + i}'
        if '\t' in raw:
            raise RenderError(f'{where}: tab character')
        if not raw.strip():
            prev_blank, i = True, i + 1
            continue
        indent = len(raw) - len(raw.lstrip(' '))
        text = raw.strip()
        if raw.startswith('```') or raw.startswith('~~~'):
            raise RenderError(f'{where}: fenced code block')
        if text.startswith('|') and text.endswith('|'):
            raise RenderError(f'{where}: table')
        m = re.match(r'^(#{1,6}) +(.*)$', raw)
        if m:
            close_all()
            out.append(('h', len(m.group(1)), m.group(2).strip(), first_line + i))
            prev_blank, i = False, i + 1
            continue
        if re.fullmatch(r'(-{3,}|\*{3,}|_{3,})', text) and indent < 4:
            close_all()
            prev_blank, i = True, i + 1
            continue
        lm = LIST_RE.match(raw)
        if lm and not (not stack and indent >= 4 and prev_blank):
            mi = len(lm.group(1))
            ordered = lm.group(2)[0].isdigit()
            content = mi + len(lm.group(2)) + 1
            while stack and stack[-1]['marker'] > mi:
                stack.pop()
            item = [('p', lm.group(3), first_line + i)]
            if stack and stack[-1]['marker'] == mi:
                stack[-1]['items'].append(item)
            else:
                lst = dict(marker=mi, content=content, ordered=ordered, items=[item])
                node = ('list', ordered, lst['items'])
                if stack:
                    stack[-1]['items'][-1].append(node)
                else:
                    out.append(node)
                stack.append(lst)
            prev_blank, i = False, i + 1
            continue
        if stack and not prev_blank:
            # continuation line of the paragraph of the deepest open item
            item = stack[-1]['items'][-1]
            if item[-1][0] != 'p':
                raise RenderError(f'{where}: continuation line after a nested block')
            item[-1] = ('p', item[-1][1] + ' ' + text, item[-1][2])
            i += 1
            continue
        if stack:
            # a new paragraph of the deepest open item whose content column the line reaches
            while stack and indent < stack[-1]['content']:
                stack.pop()
            if stack:
                stack[-1]['items'][-1].append(('p', text, first_line + i))
                prev_blank, i = False, i + 1
                continue
        if indent >= 4 and prev_blank:
            code, j = [], i
            while j < len(lines):
                r = lines[j].rstrip('\n')
                if r.strip() and len(r) - len(r.lstrip(' ')) < 4:
                    break
                code.append(r[4:] if r.strip() else '')
                j += 1
            while code and not code[-1]:
                code.pop()
            out.append(('code', code, first_line + i))
            prev_blank, i = True, j
            continue
        if out and out[-1][0] == 'p' and not prev_blank:
            out[-1] = ('p', out[-1][1] + ' ' + text, out[-1][2])
        else:
            out.append(('p', text, first_line + i))
        prev_blank, i = False, i + 1
    return out


def entry_label(title):
    m = re.match(r'^([A-Z]+-\d+):', title)
    if m:
        return 'reg:' + m.group(1)
    return 'reg:' + re.sub(r'[^a-z0-9]+', '-', re.sub(r'`[^`]*`', '', title).lower()).strip('-')


def heading(level, title, src, lineno, labels):
    cmd = {2: 'section', 3: 'subsection', 4: 'subsubsection'}.get(level)
    if cmd is None:
        raise RenderError(f'{src}:{lineno}: heading level {level} is not rendered')
    label = entry_label(title)
    if label in labels:
        raise RenderError(f'{src}:{lineno}: duplicate heading label {label}')
    labels.add(label)
    tex = inline(title, f'{src}:{lineno}', cite=False)
    return (f'\\{cmd}{{\\texorpdfstring{{{tex}}}{{{plain(title)}}}}}\\label{{{label}}}\n\n')


def tex_blocks(bs, src, labels, depth=0):
    out = []
    for b in bs:
        if b[0] == 'h':
            out.append(heading(b[1], b[2], src, b[3], labels))
        elif b[0] == 'p':
            out.append(inline(b[1], f'{src}:{b[2]}') + '\n\n')
        elif b[0] == 'code':
            body = '\\\\\n'.join(r'\texttt{' + esc(l, f'{src}:{b[2]}', code=True).replace(' ', '~') + '}'
                                 for l in b[1])
            out.append('\\begin{quote}\n' + body + '\n\\end{quote}\n\n')
        elif b[0] == 'list':
            env = 'enumerate' if b[1] else 'itemize'
            out.append(f'\\begin{{{env}}}\n')
            for item in b[2]:
                inner = tex_blocks(item, src, labels, depth + 1).strip()
                out.append('\\item ' + inner + '\n')
            out.append(f'\\end{{{env}}}\n\n')
    return ''.join(out)


def split_title(lines, src):
    if not lines or not lines[0].startswith('# '):
        raise RenderError(f'{src}:1: expected a "# " title line')
    return lines[0][2:].strip(), lines[1:]


def sections(bs, level):
    """Group blocks into (heading block or None, [blocks]) by headings of the given level."""
    groups = [(None, [])]
    for b in bs:
        if b[0] == 'h' and b[1] == level:
            groups.append((b, []))
        else:
            groups[-1][1].append(b)
    return groups


def entry_table(entries, src):
    """A booktabs table: entry id and title, one row per entry heading."""
    rows = []
    for h in entries:
        m = re.match(r'^([A-Z]+-\d+): *(.*)$', h[2])
        if not m:
            continue
        rows.append(f'\\ref{{{entry_label(h[2])}}} & {inline(m.group(2), f"{src}:{h[3]}", cite=False)} \\\\')
    return table('lp{0.8\\linewidth}', 'Entry & Title', rows)


def check_complete(src, md_lines, tex):
    """Every word of the Markdown occurs in the LaTeX at least as often: a guard against a block
    that the converter drops."""
    words = lambda t: collections.Counter(re.findall(r'[A-Za-z]{4,}', t))
    md, out = words('\n'.join(md_lines)), words(tex)
    lost = sorted(w for w in md if out[w] < md[w])
    if lost:
        raise RenderError(f'{src}: the rendering lacks occurrences of: {", ".join(lost[:10])}')


def read(path):
    with open(os.path.join(REPO, path), encoding='utf-8') as f:
        return f.read().split('\n')


def render_shipping():
    src = 'doc/SHIPPING-CHANGES.md'
    _, rest = split_title(read(src), src)
    bs = blocks(rest, src, 2)
    labels = set()
    changes = [b for b in bs if b[0] == 'h' and b[1] == 2 and re.match(r'^S-\d+:', b[2])]
    reported = [b for b in bs if b[0] == 'h' and b[1] == 3 and re.match(r'^R-\d+:', b[2])]
    out = [HEADER.format(src=src),
           '\\chapter{Shipping changes}\\label{chap:shipping-changes}\n\n',
           '\\section*{At a glance}\n\\begin{itemize}\n',
           '\\item \\lead{Source} \\code{doc/SHIPPING-CHANGES.md}, rendered by '
           '\\code{blueprint/scripts/render\\_registers.py}; every section below is the register\'s '
           'own text.\n',
           f'\\item \\lead{{Changes}} {len(changes)} entries, one commit each, subject '
           '\\code{shipping(S-<n>): ...}.\n',
           f'\\item \\lead{{Reported, not fixed}} {len(reported)} entries.\n',
           '\\end{itemize}\n\n', entry_table(changes, src), entry_table(reported, src),
           tex_blocks(bs, src, labels)]
    check_complete(src, rest, ''.join(out))
    return ''.join(out)


def render_divergences():
    src = 'doc/DIVERGENCES.md'
    _, rest = split_title(read(src), src)
    bs = blocks(rest, src, 2)
    groups = sections(bs, 2)
    labels = set()
    out = [HEADER.format(src=src), '\\chapter{Divergences}\\label{chap:divergences}\n\n']
    entries_seen = False
    body = []
    for h, content in groups:
        if h is not None and re.sub(r'`', '', h[2]).strip().lower() == 'entries':
            entries_seen = True
            sub = sections(content, 3)
            prose = sub[0][1]
            entries = [e for e, _ in sub[1:]]
            body.append(heading(2, h[2], src, h[3], labels))
            body.append(tex_blocks(prose, src, labels))
            if not entries:
                if not prose:
                    body.append('The register has no entries.\n\n')
            else:
                body.append(entry_table(entries, src))
                for e, c in sub[1:]:
                    body.append(heading(3, e[2], src, e[3], labels))
                    body.append(tex_blocks(c, src, labels))
            continue
        if h is not None:
            body.append(heading(2, h[2], src, h[3], labels))
        body.append(tex_blocks(content, src, labels))
    if not entries_seen:
        raise RenderError(f'{src}: no "## Entries" section')
    n = sum(1 for b in bs if b[0] == 'h' and b[1] == 3 and re.match(r'^D-\d+:', b[2]))
    out += ['\\section*{At a glance}\n\\begin{itemize}\n',
            '\\item \\lead{Source} \\code{doc/DIVERGENCES.md}, rendered by '
            '\\code{blueprint/scripts/render\\_registers.py}; the sections below are the register\'s '
            'own text.\n',
            f'\\item \\lead{{Entries}} {n}.\n', '\\end{itemize}\n\n'] + body
    check_complete(src, rest, ''.join(out))
    return ''.join(out)


def render_pins():
    src = 'lean-toolchain, lake-manifest.json'
    toolchain = read('lean-toolchain')[0].strip()
    manifest = json.load(open(os.path.join(REPO, 'lake-manifest.json'), encoding='utf-8'))
    rows = [f'Lean toolchain & \\code{{{esc(toolchain, "lean-toolchain", True)}}} & '
            '\\code{lean-toolchain} \\\\']
    for p in manifest['packages']:
        how = 'inherited from a dependency' if p.get('inherited') else 'required by \\code{lakefile.toml}'
        inp = p.get('inputRev') or ''
        pinned = 'pinned by commit' if inp == p['rev'] else f'input \\code{{{esc(inp, "manifest", True)}}}'
        rows.append(f'\\code{{{esc(p["name"], "manifest", True)}}} & '
                    f'\\code{{{esc(p.get("url", ""), "manifest", True)}}} at \\code{{{p["rev"][:8]}}}'
                    f' ({pinned}) & {how} \\\\')
    return (HEADER.format(src=src) + '\\begin{tabular}{lp{0.5\\linewidth}l}\n\\toprule\n'
            'Pin & Value & Source \\\\\n\\midrule\n' + '\n'.join(rows) + '\n\\bottomrule\n\\end{tabular}\n')


OUTPUTS = {'shipping-changes.tex': render_shipping, 'divergences.tex': render_divergences,
           'pins.tex': render_pins}


def main(argv):
    check = '--check' in argv
    stale = []
    try:
        rendered = {name: f() for name, f in OUTPUTS.items()}
    except RenderError as e:
        print(f'render_registers: error: {e}', file=sys.stderr)
        return 2
    os.makedirs(OUT, exist_ok=True)
    for name, text in rendered.items():
        path = os.path.join(OUT, name)
        old = open(path, encoding='utf-8').read() if os.path.exists(path) else None
        if old == text:
            continue
        if check:
            stale.append(name)
        else:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(text)
            print(f'render_registers: wrote blueprint/src/generated/{name}')
    if stale:
        print('render_registers: stale: ' + ', '.join(stale) + ' (run blueprint/scripts/render_registers.py)')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
